/**
 * DE Cup Player Domain Types
 *
 * Permanent player information only.
 *
 * Statistics are generated by the Tournament Engine.
 */

export enum PlayerStatus {
  ACTIVE = 'ACTIVE',

  INACTIVE = 'INACTIVE',
}

export interface Player {
  id: string;

  displayName: string;

  shortName?: string;

  avatarUrl?: string;

  status: PlayerStatus;

  createdAt: Date;

  updatedAt: Date;
}

export interface PlayerProfile {
  playerId: string;

  displayName: string;

  avatarUrl?: string;

  status: PlayerStatus;
}

export interface PlayerSummary {
  playerId: string;

  displayName: string;

  seasonsPlayed: number;

  matchesPlayed: number;
}

export interface CreatePlayerRequest {
  displayName: string;

  shortName?: string;

  avatarUrl?: string;
}

export interface UpdatePlayerRequest {
  displayName?: string;

  shortName?: string;

  avatarUrl?: string;

  status?: PlayerStatus;
}
